module.exports = { total: 22058,
  per_page: 10,
  last_page: 2206,
  page: 1,
  projects:
      [ { id: 1313,
        url: 'https://hackaday.io/project/1313-openmv',
        owner_id: 10526,
        name: 'OpenMV',
        summary: 'Python-powered machine vision modules',
        description:
            'The OpenMV project aims at making machine vision more accessible to beginners by developing a user-friendly, open-source, low-cost machine vision platform.\r\n\r\nOpenMV cameras are programmable in Python3 and come with an extensive set of image processing functions such as face detection, keypoints descriptors, color tracking, QR and Bar codes decoding, AprilTags, GIF and MJPEG recording and more.\r\n\r\nAdditionally, OpenMV includes a cross-platform IDE (based on Qt Creator) designed specifically to support programmable cameras. The IDE allows viewing the camera&apos;s frame buffer, accessing sensor controls, uploading scripts to the camera via serial over USB (or WiFi/BLE if available) and includes a set of image processing tools to generate tags, thresholds, keypoints etc...\r\n\r\nThe OpenMV project is a THP semifinalist and was successfully funded via Kickstarter back in 2015 and has come a long way since then.',
        image_url: 'https://cdn.hackaday.io/images/5817461406329458960.JPG',
        views: 204975,
        comments: 211,
        followers: 3593,
        skulls: 1370,
        logs: 19,
        details: 1,
        instruction: 0,
        components: 10,
        images: 6,
        created: 1401763612,
        updated: 1554388653,
        tags: [Array] },
        { id: 5373,
          url: 'https://hackaday.io/project/5373-hack-chat',
          owner_id: 182178,
          name: 'Hack Chat',
          summary:
              'Use the team chat to talk about your projects and find collaborators for whatever you are working on.',
          description:
              'If you need help on your project you&apos;ve come to the right place. \r\nClick on the &quot;Public Chat&quot; button on the left top and you&apos;re automatically in. \r\n\r\nThose that just want to talk about hacking have found the place as well. All are welcome!',
          image_url: 'https://cdn.hackaday.io/images/7255311484679597966.png',
          views: 54205,
          comments: 193,
          followers: 2526,
          skulls: 1366,
          logs: 0,
          details: 1,
          instruction: 1,
          components: 0,
          images: 3,
          created: 1429655720,
          updated: 1561018687,
          tags: [Array] },
        { id: 19035,
          url:
              'https://hackaday.io/project/19035-zerophone-a-raspberry-pi-smartphone',
          owner_id: 61401,
          name: 'ZeroPhone - a Raspberry Pi smartphone',
          summary:
              'Pi Zero-based open-source mobile phone (that you can assemble for 50$ in parts)',
          description:
              'This is a mobile phone that:\r\n\r\n- First and foremost, will be a well-working reliable phone\r\n- Is as open-source as possible *while also being cheap*\r\n- Can be assembled and repaired independently\r\n- Is easy to get parts for\r\n- Doesn&apos;t have apps with privacy concerns\r\n- Allows to write your own apps in Python\r\n\r\nIt costs about 50$ in parts, and all the parts are available on eBay/TaoBao/etc, most of the phone can be assembled with just a soldering iron. User interface is written using Python \r\nand is being morphed into a lightweight phone-tailored UI framework.\r\n\r\nA crowdfunded manufacturing run is expected in a month - kits will be available, as well as a small batch of fully-assembled phones. Subscribe to newsletter below!',
          image_url: 'https://cdn.hackaday.io/images/7473031508515021059.jpg',
          views: 359914,
          comments: 148,
          followers: 1639,
          skulls: 1151,
          logs: 50,
          details: 1,
          instruction: 10,
          components: 27,
          images: 5,
          created: 1482175178,
          updated: 1552196301,
          tags: [Array] },
        { id: 3800,
          url: 'https://hackaday.io/project/3800-3d-printable-robot-arm',
          owner_id: 2561,
          name: '3D Printable Robot Arm',
          summary:
              'A printable robot arm, a little bigger than the usual hobby servo once.  ',
          description:
              'My printable robot arm is inspired by the well known industry robots, but printable.\r\nThe goal is to develop a open source robot arm to use in private or small businesses and make robot development available for every one.  \r\nThe arm should lift about 2 kg enough to perform every day tasks.  Currently robot arms are expensive or small and weak, or clumpy. \r\nIndustrial robots are expensive and dangerous and for that not suitable for using at home or schools. \r\nA Open Source printable robot can build,used and developed by every one. \r\nRobots are still expensive and hard to operate, but this must not longer be the case. \r\nA cheap 3d printed robot arm could be used by disabled persons to manage their daily needs better and more independent. Operate at dangerous but not so developed places. \r\nRemote controlled you could even us the robot to open your door if you forgot your keys.\r\n\r\nThe future Arm will include a moving base. \r\n',
          image_url: 'https://cdn.hackaday.io/images/848911460535166971.jpg',
          views: 204954,
          comments: 106,
          followers: 2056,
          skulls: 1144,
          logs: 19,
          details: 1,
          instruction: 1,
          components: 4,
          images: 6,
          created: 1420754811,
          updated: 1563280237,
          tags: [Array] },
        { id: 13466,
          url:
              'https://hackaday.io/project/13466-raspberry-pi-smart-mirror',
          owner_id: 148563,
          name: 'Raspberry Pi Smart Mirror',
          summary:
              'A mirror which displays applications, other useful information',
          description:
              'In this video, we show you how to make an easy raspberry pi powered home smart mirror. It displays applications so that you can check the weather and local news while you are getting ready in the morning. It&apos;s also modular, so you can easy move it around or hang it on the wall if you like.  We&apos;ve created a basic application that you can run on the mirror, but it&apos;s totally customizable if you want to write some of your own code. \r\n\r\nIn the future, we plan to add AI components to make this fully automated. We are drawing inspiration from this project:  <a href="https://www.youtube.com/watch?v=sc9UbREmo58" target="_blank">https://www.youtube.com/watch?v=sc9UbREmo58</a>. Stay tuned for a future video about that!',
          image_url: 'https://cdn.hackaday.io/images/4075911473092005133.jpg',
          views: 168712,
          comments: 30,
          followers: 1828,
          skulls: 1085,
          logs: 0,
          details: 1,
          instruction: 0,
          components: 6,
          images: 1,
          created: 1473092117,
          updated: 1562854669,
          tags: [Array] },
        { id: 1538,
          url: 'https://hackaday.io/project/1538-portablesdr',
          owner_id: 9087,
          name: 'PortableSDR',
          summary:
              'Fully stand-alone HF (Shortwave) Software Defined Transceiver & Vector Network Analyzer. Designed for rugged portable use. Highly hackable.',
          description:
              'The PSDR is a completely stand-alone (no computer needed), compact, Portable Software Defined Transceiver (hence the name, sorta). Originally designed for backpacking use by Ham Radio operators. It includes complete coverage up to about 30Mhz (plus 144Mhz), it has a 168Mhz ARM processor, color display, and an innovative interface.\r\n\r\nVector Network Analysis (which includes antenna analysis) and GPS functions are included.\r\n\r\nThe entire design is Open Source. The electronics are designed and laid out to be easy to understand and tinker with. In addition to source code, schematics, board layout and parts lists, articles and videos describing the theory of the design are being created.',
          image_url: 'https://cdn.hackaday.io/images/7760611421216476601.jpg',
          views: 194071,
          comments: 200,
          followers: 2378,
          skulls: 1001,
          logs: 28,
          details: 1,
          instruction: 8,
          components: 16,
          images: 6,
          created: 1403234611,
          updated: 1555630231,
          tags: [Array] },
        { id: 283,
          url: 'https://hackaday.io/project/283-pcb-mill-for-under-10',
          owner_id: 894,
          name: 'PCB mill for under $10',
          summary:
              'pcb mill built from garbage using basic hand tools and little money',
          description:
              'A gradually improving attempt to make a useful pcb mill out of a printer and other assorted garbage, with a minimal budget and no fancy tools. It works!, but let\'s see how much better it can be.',
          image_url: 'https://cdn.hackaday.io/images/9555871394520169199.jpg',
          views: 214412,
          comments: 62,
          followers: 2541,
          skulls: 961,
          logs: 9,
          details: 1,
          instruction: 0,
          components: 11,
          images: 6,
          created: 1393891681,
          updated: 1552165567,
          tags: [Array] },
        { id: 12211,
          url:
              'https://hackaday.io/project/12211-arduino-glasses-a-hmd-for-multimeter',
          owner_id: 55607,
          name: 'Arduino Glasses a HMD for Multimeter',
          summary:
              'Building an HMD with no special parts, to make work easier and safer',
          description:
              'Trying to build a cheap Arduino Data Glasses for everybody.<br>It&apos;s working, and now it can even help to avoid accidents. From the first idea to the working prototype, it took 4 Month<br><br>The challenge was, that It should be constructed out of common materials that can be found easily.<br>The project is more about how to build the optical system for this HMD<br>I have a few ideas and one of them is to connect it to a Multimeter over Bluetooth to get the Data right in front of my eyes.<br>One thing is clear, you can not just place a screen in front of your eyes, because it will not be possible for them to focus it.<br><br>In the logs you can see from the first tests to what I have now. <br>The whole project runs under Open Source License.<br><br>And please, if you use my design, do not forget to mention that it is based on my idea and add a link to my homepage <a target="_blank" rel="noopener noreferrer" href="http://www.alainsprojects.com">www.alainsprojects.com</a>.<br>Thank y',
          image_url: 'https://cdn.hackaday.io/images/2744261482922947650.jpg',
          views: 242153,
          comments: 93,
          followers: 1263,
          skulls: 907,
          logs: 37,
          details: 1,
          instruction: 6,
          components: 9,
          images: 6,
          created: 1465843545,
          updated: 1562608591,
          tags: [Array] },
        { id: 2040,
          url: 'https://hackaday.io/project/2040-web-security-everywhere',
          owner_id: 19546,
          name: 'Web security everywhere',
          summary:
              'Secure your Internet, control your data, fight censorship.\r\nBring your autonomous all in one privacy device everywhere.',
          description:
              'In a world where digital privacy doesn\'t exist anymore, where journalists couldn\'t securely do their work, where companies are spyed upon by various entities, and where Human Rights are cynically disregarded, there is an urgent need for an easy-to-use tool to restore digital privacy.\r\n\r\nThis autonomous device uses the available connectivity to build a secure access-point and bypasses internet filters to connect to a remote network, use a secured internet or even browse anonymously.\r\nConnect your laptop/smartphone to the device\'s secured wifi access-point, no additional setup is needed. Enjoy a secured internet anywhere, anytime.\r\n\r\nIt could connect the internet via a public wifi access-point, 3G internet via phone usb/wifi tethering, corporate cable network, or even your own router/ADSL box.\r\n\r\nIt is very easy to use with its touch control interface and its fully automatized functions.\r\n\r\nIt could run autonomously during several hours on its internal battery.',
          image_url: 'https://cdn.hackaday.io/images/8176021410091861327.JPG',
          views: 178196,
          comments: 38,
          followers: 3688,
          skulls: 899,
          logs: 31,
          details: 1,
          instruction: 6,
          components: 10,
          images: 5,
          created: 1406155716,
          updated: 1560728833,
          tags: [Array] },
        { id: 1395,
          url:
              'https://hackaday.io/project/1395-open-source-science-tricorder',
          owner_id: 11110,
          name: 'Open Source Science Tricorder',
          summary:
              'Science in your hand.  A pocket-sized instrument capable of visualizing and exploring the world around you. ',
          description:
              'It is my deep belief that knowledge brings about positive change. \r\n\r\nWe could live in a world where the same instrument that can show a child how much chlorophyll is in a leaf could also show how them much pollution is in the air around us, or given off by one\'s car. As an educator and a researcher, I feel that if people could easily discover things about their worlds that were also important social topics, that they would then make positive social choices, like reducing their emissions, or petitioning for cleaner industry in their communities. \r\n\r\nBy having access to general inexpensive sensing tools, people can learn about healthy leaves, clean air, clouds and the water cycle, energy efficient homes — and visualize abstract concepts like spectra or magnetism.\r\n\r\nAs a tool for exploration, we can discover things around us that we don\'t already know. And that\'s what it\'s about. Little discoveries, everywhere. ',
          image_url: 'https://cdn.hackaday.io/images/3776181414477226534.jpg',
          views: 121156,
          comments: 91,
          followers: 3057,
          skulls: 879,
          logs: 17,
          details: 1,
          instruction: 3,
          components: 31,
          images: 6,
          created: 1402115599,
          updated: 1552049295,
          tags: [Array] } ],
  users:
      { '894':
            { id: 894,
              url: 'https://hackaday.io/shlonkin',
              username: 'shlonkin',
              screen_name: 'shlonkin',
              rank: 127,
              image_url: 'https://cdn.hackaday.io/images/7200201393548662814.JPG',
              followers: 16973,
              following: 1,
              projects: 19,
              skulls: 1897,
              location: 'Kure, Hiroshima, Japan',
              about_me: 'garbage tinkerer, kindergarten teacher, baker, dad',
              who_am_i:
                  'I&apos;m a long time mechanical and electronics tinkerer who can&apos;t resist the call of the garbage pile. I teach kindergarten, raise my own kid, and if there&apos;s any time left, I make stuff.',
              what_i_have_done: '',
              what_i_would_like_to_do:
                  'I&apos;m an avid tinkerer who loves getting inspiration and education from the projects I see on HaD. I hope my own projects can be enjoyed by others in the same way.',
              created: 0,
              tags: [Array] },
        '2561':
            { id: 2561,
              url: 'https://hackaday.io/4ndreas',
              username: '4ndreas',
              screen_name: 'Andreas Hoelldorfer',
              rank: 439,
              image_url: 'https://cdn.hackaday.io/images/9031811501627301322.jpeg',
              followers: 122,
              following: 13,
              projects: 3,
              skulls: 1160,
              location: 'Karlsruhe, Germany',
              about_me:
                  'I\'m a inventor and maker my hole live. I don\'t hesitate if something is possible I try it.',
              who_am_i: '',
              what_i_have_done: '',
              what_i_would_like_to_do: 'Hack the Planet!',
              created: 0,
              tags: null },
        '9087':
            { id: 9087,
              url: 'https://hackaday.io/michaelrcolton',
              username: 'michaelrcolton',
              screen_name: 'Michael R Colton',
              rank: 1427,
              image_url:
                  'https://cdn.hackaday.io/images/1295301403243080800.jpg?r=x&s=400&r=x&s=400&r=x&s=400&r=x&s=400&r=x&s=400&r=x&s=400',
              followers: 825,
              following: 2,
              projects: 2,
              skulls: 1006,
              location: 'American Fork, Utah, USA',
              about_me:
                  'Self-taught Engineer & Designer - \r\nMore Electronic than Human',
              who_am_i:
                  'Hi there. I\'ve been breaking things since I was a kid. Only recently did I learn how to make things. In college, I turned down engineering because I thought I\'d never understand electronics, got my psychology degree instead. Now I\'m an electrical engineer and product designer, go figure.\r\n\r\nI also bike, climb, backpack, and paraglide. I draw and digital paint. I enjoy photography. I have a thing for radio waves. I love Asia and study Mandarin and Japanese.\r\n\r\nI\'m married to a wonderful wife!',
              what_i_have_done: '',
              what_i_would_like_to_do: 'I love hackaday. Where else would I host my projects?',
              created: 0,
              tags: null },
        '10526':
            { id: 10526,
              url: 'https://hackaday.io/iabdalkader',
              username: 'iabdalkader',
              screen_name: 'i.abdalkader',
              rank: 1855,
              image_url:
                  'https://cdn.hackaday.io/images/3873461401740841534.jpeg?r=x&s=400&r=x&s=400',
              followers: 10435,
              following: 0,
              projects: 2,
              skulls: 1438,
              location: 'Egypt',
              about_me: 'I like to make things :)',
              who_am_i: 'I\'m a maker/programmer/hobbyist',
              what_i_have_done: '',
              what_i_would_like_to_do:
                  'Mainly because of the HaD Prize, but also getting feedback on my projects is invaluable to me, so that too. ',
              created: 0,
              tags: null },
        '11110':
            { id: 11110,
              url: 'https://hackaday.io/peterjansen',
              username: 'peterjansen',
              screen_name: 'peter jansen',
              rank: 239,
              image_url: 'https://cdn.hackaday.io/images/4783201402113470617.jpg',
              followers: 974,
              following: 1,
              projects: 7,
              skulls: 1269,
              location: 'Canada / USA',
              about_me: 'postdoctoral research fellow and open source mad scientist',
              who_am_i:
                  'trying to make the world a better place, through knowledge, educational outreach, and humility.\r\n\r\ni have an interdisciplinary educational background in cognitive artificial intelligence, computational neuroscience, and spectroscopy.  by day i try to teach computers to learn language likes babies do, and by night i work to design open source tools for science education.',
              what_i_have_done: '',
              what_i_would_like_to_do: '',
              created: 0,
              tags: [Array] },
        '19546':
            { id: 19546,
              url: 'https://hackaday.io/arcadialabs',
              username: 'arcadialabs',
              screen_name: 'Arcadia Labs',
              rank: 389,
              image_url: 'https://cdn.hackaday.io/images/8828051432341058854.png',
              followers: 889,
              following: 4,
              projects: 6,
              skulls: 1091,
              location: 'France',
              about_me:
                  'Hardware and software hacker / developer, computers science specialist.\r\nCurrently looking for a job / contracts.',
              who_am_i:
                  'Since I was a child, I\'ve had a brain full of ideas but not the right skills to build them. I\'m a self-taught person, so I learned programming, electronics, and a lot of other skills.\r\nI mainly focus on computers, SoC, microcontrollers.\r\nI am also an IT specialist, working for end-users or corporations. \r\nArcadia Labs is my own company and I use it to spread the word about open-source philosophy.\r\nI\'m also co-founder of hardware-libre.fr open-hardware weblog.',
              what_i_have_done: '',
              what_i_would_like_to_do:
                  'I see technology heading in a wrong direction : devices are built to break, and big corporations don\'t care about innovation anymore. \r\nI see people are getting really upset about these practices.\r\nI think this is now creating a huge opportunity for people that build well designed technology and think out of the box.\r\n\r\nI am also a creative person and I constantly need to learn something new. Projects are also a great way to teach people interesting things.',
              created: 0,
              tags: [Array] },
        '55607':
            { id: 55607,
              url: 'https://hackaday.io/awall99',
              username: 'awall99',
              screen_name: 'Alain Mauer',
              rank: 41,
              image_url: 'https://cdn.hackaday.io/images/9002251472984252003.jpg',
              followers: 86,
              following: 86,
              projects: 15,
              skulls: 1262,
              location: 'Luxemburg (Planet Earth)',
              about_me: 'My brain can\'t sleep and finally I know why.',
              who_am_i: 'Hi, I am Alain and I love finding solutions',
              what_i_have_done: '',
              what_i_would_like_to_do: 'To share strange ideas',
              created: 0,
              tags: [Array] },
        '61401':
            { id: 61401,
              url: 'https://hackaday.io/CRImier',
              username: 'CRImier',
              screen_name: 'Arsenijs',
              rank: 9,
              image_url: 'https://cdn.hackaday.io/images/2397071428544147585.jpg',
              followers: 185,
              following: 115,
              projects: 32,
              skulls: 1629,
              location: 'Latvia',
              about_me:
                  'I&apos;ve got experiments to run, there&apos;s engineering to be done\r\nFor the goals that are yet to be reached',
              who_am_i:
                  'A guy who works with electronics and coding - mainly Python - as well as has a truckload of ideas, big and small.',
              what_i_have_done: '',
              what_i_would_like_to_do:
                  'Because <a href="http://Hackaday.io" target="_blank">Hackaday.io</a>. Oh, and Hackaday Prize!',
              created: 0,
              tags: [Array] },
        '148563':
            { id: 148563,
              url: 'https://hackaday.io/HackerHouse',
              username: 'HackerHouse',
              screen_name: 'Hacker House',
              rank: 469,
              image_url: 'https://cdn.hackaday.io/images/7550701466125051605.jpg',
              followers: 91,
              following: 35,
              projects: 8,
              skulls: 1393,
              location: 'Santa Clara, California',
              about_me: 'We make things.',
              who_am_i: '',
              what_i_have_done: '',
              what_i_would_like_to_do: '',
              created: 0,
              tags: [Array] },
        '182178':
            { id: 182178,
              url: 'https://hackaday.io/Lutetium',
              username: 'Lutetium',
              screen_name: 'Lutetium',
              rank: 1847,
              image_url: 'https://cdn.hackaday.io/images/265831479737328093.png',
              followers: 245,
              following: 121,
              projects: 5,
              skulls: 2833,
              location: 'The Internet',
              about_me:
                  '<a href="http://Hackaday.io" target="_blank">Hackaday.io</a> Community Manager',
              who_am_i:
                  'Lutetium-176 is a relatively abundant (2.5%) radioactive isotope with a half-life of about 38 billion years used to determine the age of meteorites.',
              what_i_have_done: '',
              what_i_would_like_to_do: '',
              created: 0,
              tags: null } } }

